---
# Role tasks

- name: Find out what Dns records could be overwriten
  win_dns_record:
    state: absent
    name: >-
      {{ win_dns_records_item.name
         | default(omit) }}
    type: >-
      {{ win_dns_records_item.type
         | default(omit) }}
    zone: >-
      {{ win_dns_records_item.zone
         | default(omit) }}
    ttl: >-
      {{ win_dns_records_item.ttl
         | default(omit) }}
    computer_name: >-
      {{ win_dns_records_item.computer_name
         | default(omit) }}
  when: >-
    (not win_dns_records_item.overwrite | default(True))
    and (win_dns_records_item.state | default('present')) == 'present'
  loop: "{{ win_dns_records_to_manage }}"
  loop_control:
    loop_var: win_dns_records_item
    index_var: win_dns_records_index
    label: >-
      [{{ win_dns_records_item.type | default('') }}]
      {{ win_dns_records_item.name | default('') }} -
      {{ win_dns_records_item.value | default('') }}
  no_log: "{{ win_dns_records_no_log }}"
  vars:
    win_dns_records_to_manage: >-
      {{ win_dns_records
         + ((win_dns_records_load_from_hostvars)
            | ternary(win_dns_records_hostvars
                      | default([])
                      | flatten, [])) }}
  check_mode: yes
  register: get_dns_result
  tags:
    - role::win_dns_records

- name: Setup dns records
  win_dns_record:
    name: >-
      {{ win_dns_records_item.name
         | default(omit) }}
    type: >-
      {{ win_dns_records_item.type
         | default(omit) }}
    value: >-
      {{ win_dns_records_item.value
         | default(omit) }}
    zone: >-
      {{ win_dns_records_item.zone
         | default(omit) }}
    state: >-
      {{ win_dns_records_item.state
         | default(omit) }}
    ttl: >-
      {{ win_dns_records_item.ttl
         | default(omit) }}
    computer_name: >-
      {{ win_dns_records_item.computer_name
         | default(omit) }}
  # noqa 503
  when: >-
    ((win_dns_records_item.state | default('present')) == 'absent')
    | ternary(True,
      (win_dns_records_item.overwrite | default(True))
      or not get_dns_result.results[win_dns_records_index].changed)
  loop: "{{ win_dns_records_to_manage }}"
  loop_control:
    loop_var: win_dns_records_item
    index_var: win_dns_records_index
    label: >-
      [{{ win_dns_records_item.type | default('') }}]
      {{ win_dns_records_item.name | default('') }} -
      {{ win_dns_records_item.value | default('') }}
      {{ get_dns_result.results[win_dns_records_index].changed
      | ternary('♻️  overwrite','')}}
  no_log: "{{ win_dns_records_no_log }}"
  vars:
    win_dns_records_to_manage: >-
      {{ win_dns_records
         + ((win_dns_records_load_from_hostvars)
            | ternary(win_dns_records_hostvars
                      | default([])
                      | flatten, [])) }}
  register: set_dns_result
  tags:
    - role::win_dns_records
