---
# Role tasks


- name: Avoid overwrites
  include_tasks: check.yml
  when: win_dns_records_fail_all_on_overwrite

- name: Setup DNS records
  win_dns_record:
    name: >-
      {{ win_dns_records_item.name
         | default(omit) }}
    type: >-
      {{ win_dns_records_item.type
         | default(omit) }}
    value: >-
      {{ win_dns_records_item.value
         | default(omit) }}
    zone: >-
      {{ win_dns_records_item.zone
         | default(omit) }}
    state: >-
      {{ win_dns_records_item.state
         | default(omit) }}
    ttl: >-
      {{ win_dns_records_item.ttl
         | default(omit) }}
    computer_name: >-
      {{ win_dns_records_item.computer_name
         | default(omit) }}
  vars:
    win_dns_records_to_manage: >-
      {{ win_dns_records
         + ((win_dns_records_load_from_hostvars)
            | ternary(win_dns_records_hostvars
                      | default([])
                      | flatten, [])) }}
  loop: "{{ win_dns_records_to_manage }}"
  loop_control:
    loop_var: win_dns_records_item
    index_var: win_dns_records_index
    label: >-
      [{{ win_dns_records_item.type | default('') }}]
      {{ win_dns_records_item.name | default('') }} -
      {{ win_dns_records_item.value | default('') }}
  no_log: "{{ win_dns_records_no_log }}"
  tags:
    - role::win_dns_records
