---

- name: Converge
  hosts: molecule_hosts
  tasks:
    - name: Block needed to ignore errors
      ignore_errors: yes
      block:
        - name: >-
            Test win_dns_records - add existing record - fail on overwrite: yes
          vars:
            win_dns_records_fail_all_on_overwrite: yes
            win_dns_records:
            - zone: '{{ win_dns_record_zone }}'
              name: test1
              value: 1.2.3.11
              type: A
              state: present
          include_role:
            name: amtega.win_dns_records
            allow_duplicates: yes

        - name: >-
            Test win_dns_records - add existing record
            - fail on overwrite: default
          vars:
            win_dns_records:
            - zone: '{{ win_dns_record_zone }}'
              name: test2
              value: 1.2.3.12
              type: A
              state: present
          include_role:
            name: amtega.win_dns_records
            allow_duplicates: yes

    - name: 'Test win_dns_records - add existing record - fail on overwrite: no'
      vars:
        win_dns_records_fail_all_on_overwrite: no
        win_dns_records:
        - zone: '{{ win_dns_record_zone }}'
          name: test3
          value: 1.2.3.13
          type: A
          state: present
        - zone: '{{ win_dns_record_revzone }}'
          name: 13
          value: "test3.{{ win_dns_record_zone }}"
          type: PTR
          overwrite: yes
      include_role:
        name: amtega.win_dns_records
        allow_duplicates: yes

    - name: 'Test win_dns_records - remove record - fail on overwrite: no'
      vars:
        win_dns_records_fail_all_on_overwrite: no
        win_dns_records:
        - zone: '{{ win_dns_record_zone }}'
          name: test4
          type: A
          state: absent
      include_role:
        name: amtega.win_dns_records
        allow_duplicates: yes

    - name: 'Test win_dns_records - remove record - fail on overwrite: no'
      vars:
        win_dns_records_fail_all_on_overwrite: yes
        win_dns_records:
        - zone: '{{ win_dns_record_zone }}'
          name: test5
          type: A
          state: absent
      include_role:
        name: amtega.win_dns_records
        allow_duplicates: yes

    - name: 'Test win_dns_records - add new record - fail on overwrite: yes'
      vars:
        win_dns_records_fail_all_on_overwrite: yes
        win_dns_records:
        - zone: '{{ win_dns_record_zone }}'
          name: test6
          value: 1.2.3.6
          type: A
          state: present
      include_role:
        name: amtega.win_dns_records
        allow_duplicates: yes

    - name: 'Test win_dns_records - add new record - fail on overwrite: no'
      vars:
        win_dns_records_fail_all_on_overwrite: no
        win_dns_records:
        - zone: '{{ win_dns_record_zone }}'
          name: test7
          value: 1.2.3.7
          type: A
          state: present
      include_role:
        name: amtega.win_dns_records
        allow_duplicates: yes
