---

dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: WindowsServer
    box: jborean93/WindowsServer2016
    memory: 2048
    instance_raw_config_args:
      - 'vm.network "private_network", ip: "192.168.33.100"'
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    hosts:
      all:
        vars:
          win_dns_record_zone: test.ansible.local
          win_dns_record_revzone: 3.2.1.in-addr.arpa
          win_dns_record_revzone_network: 1.2.3.0/24
          win_dns_record_revzone2: 2.1.in-addr.arpa
          win_dns_record_revzone_network2: 1.2.0.0/16
          win_dns_record_revzone3: 1.in-addr.arpa
          win_dns_record_revzone_network3: 1.0.0.0/8
          win_dns_records_no_log: no
        children:
          windows:
            hosts:
              WindowsServer:
                ansible_host: 127.0.0.1
                ansible_user: vagrant
                ansible_password: vagrant
                ansible_port: 55986
                ansible_connection: winrm
                ansible_winrm_transport: ntlm
                ansible_winrm_server_cert_validation: ignore

verifier:
  name: testinfra
  lint:
    name: flake8
