---

dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  set -e
  export ANSIBLE_ACTION_PLUGINS=$PWD/action_plugins
  export ANSIBLE_BECOME_PLUGINS=$PWD/become_plugins
  export ANSIBLE_CACHE_PLUGINS=$PWD/cache_plugins
  export ANSIBLE_CALLBACK_PLUGINS=$PWD/callback_plugins
  export ANSIBLE_CLICONF_PLUGINS=$PWD/cliconf_plugins
  export ANSIBLE_CONNECTION_PLUGINS=$PWD/connection_plugins
  export ANSIBLE_DOC_FRAGMENT_PLUGINS=$PWD/doc_fragment_plugins
  export ANSIBLE_FILTER_PLUGINS=$PWD/filter_plugins
  export ANSIBLE_HTTPAPI_PLUGINS=$PWD/httpapi_plugins
  export ANSIBLE_INVENTORY_PLUGINS=$PWD/inventory_plugins
  export ANSIBLE_LIBRARY=$PWD/library
  export ANSIBLE_LOOKUP_PLUGINS=$PWD/lookup_plugins
  export ANSIBLE_NETCONF_PLUGINS=$PWD/netconf_plugins
  export ANSIBLE_STRATEGY_PLUGINS=$PWD/strategy_plugins
  export ANSIBLE_TERMINAL_PLUGINS=$PWD/terminal_plugins
  export ANSIBLE_TEST_PLUGINS=$PWD/test_plugins
  export ANSIBLE_VARS_PLUGINS=$PWD/vars_plugins
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: "WindowsServer-${INSTANCE_UUID:-1}"
    box: jborean93/WindowsServer2016
    memory: 2048
    instance_raw_config_args:
      - 'vm.network "private_network", ip: "192.168.33.100"'
provisioner:
  name: ansible
  inventory:
    hosts:
      molecule_hosts:
        hosts:
          WindowsServer-${INSTANCE_UUID:-1}:
            ansible_host: 127.0.0.1
            ansible_user: vagrant
            ansible_password: vagrant
            ansible_port: 55986
            ansible_connection: winrm
            ansible_winrm_transport: ntlm
            ansible_winrm_server_cert_validation: ignore
        vars:
          win_dns_record_zone: test.ansible.local
          win_dns_record_revzone: 3.2.1.in-addr.arpa
          win_dns_record_revzone_network: 1.2.3.0/24
          win_dns_record_revzone2: 2.1.in-addr.arpa
          win_dns_record_revzone_network2: 1.2.0.0/16
          win_dns_record_revzone3: 1.in-addr.arpa
          win_dns_record_revzone_network3: 1.0.0.0/8

verifier:
  name: ansible
