---

dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
    requirements-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: "${MOLECULE_SCENARIO_DIRECTORY}/linters.sh"
platforms:
  - name: "WindowsServer-${INSTANCE_UUID:-1}"
    box: jborean93/WindowsServer2016
    memory: 2048
    instance_raw_config_args:
      - 'vm.network "private_network", ip: "192.168.33.100"'
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_enabled: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    hosts:
      molecule_hosts:
        hosts:
          WindowsServer-${INSTANCE_UUID:-1}:
            ansible_host: 127.0.0.1
            ansible_user: vagrant
            ansible_password: vagrant
            ansible_port: 55986
            ansible_connection: winrm
            ansible_winrm_transport: ntlm
            ansible_winrm_server_cert_validation: ignore
        vars:
          win_dns_record_zone: test.ansible.local
          win_dns_record_revzone: 3.2.1.in-addr.arpa
          win_dns_record_revzone_network: 1.2.3.0/24
          win_dns_record_revzone2: 2.1.in-addr.arpa
          win_dns_record_revzone_network2: 1.2.0.0/16
          win_dns_record_revzone3: 1.in-addr.arpa
          win_dns_record_revzone_network3: 1.0.0.0/8

verifier:
  name: ansible
