---

- name: Prepare
  hosts: molecule_hosts
  tasks:
    - name: Win ping pdc
      win_ping:
      register: ping_result

    - name: Prepare DNS
      block:
        - name: Check if feature is availble
          win_shell: >-
            if (Get-Command -Name Add-WindowsFeature \
            -ErrorAction SilentlyContinue) { $true } else { $false }
          changed_when: no
          register: module_available

        - name: Ensure DNS services are installed
          win_feature:
            name: DNS
            state: present
          when: module_available.stdout | trim | bool
          register: dns_install

        - name: Reboot server if needed
          win_reboot:
          when: dns_install.reboot_required | bool

        - name: Clean slate
          import_tasks: clean.yml
          vars:
            fail_on_missing: no

        - name: Create the forward zone
          win_shell: >-
            Add-DnsServerPrimaryZone
            -Name '{{ win_dns_record_zone }}'
            -ZoneFile '{{ win_dns_record_zone }}.dns'

        - name: Create the reverse zone
          win_shell: >-
            Add-DnsServerPrimaryZone
            -NetworkID '{{ win_dns_record_revzone_network }}'
            -ZoneFile '{{ win_dns_record_revzone }}.dns'

        - name: Create the reverse zone 2
          win_shell: >-
            Add-DnsServerPrimaryZone
            -NetworkID '{{ win_dns_record_revzone_network2 }}'
            -ZoneFile '{{ win_dns_record_revzone2 }}.dns'

        - name: Create the reverse zone 3
          win_shell: >-
            Add-DnsServerPrimaryZone
            -NetworkID '{{ win_dns_record_revzone_network3 }}'
            -ZoneFile '{{ win_dns_record_revzone3 }}.dns'

    - name: Prepare DNS records for testing
      vars:
        test_numbers: "{{ range(1,6) | list }}"
      block:

        - name: 'Prepare win_dns_records - remove records'
          vars:
            win_dns_records:
            - zone: '{{ win_dns_record_zone }}'
              name: "test{{ test_number }}"
              type: A
              state: absent
          include_role:
            name: amtega.win_dns_records
            allow_duplicates: yes
          loop: "{{ test_numbers }}"
          loop_control:
            loop_var: test_number
            label: "test{{ test_number }}"

        - name: 'Prepare win_dns_records - add records'
          vars:
            win_dns_records:
            - zone: '{{ win_dns_record_zone }}'
              name: "test{{ test_number }}"
              value: "1.2.3.{{ test_number }}"
              type: A
              state: present
          include_role:
            name: amtega.win_dns_records
            allow_duplicates: yes
          loop: "{{ test_numbers }}"
          loop_control:
            loop_var: test_number
            label: "test{{ test_number }}"
