---

- name: Prepare
  hosts: all
  tasks:
    - name: Win ping pdc
      win_ping:
      register: ping_result

    - name: Prepare DNS
      block:
        - name: Check if feature is availble
          win_shell: >-
            if (Get-Command -Name Add-WindowsFeature \
            -ErrorAction SilentlyContinue) { $true } else { $false }
          changed_when: no
          register: module_available

        - name: Ensure DNS services are installed
          win_feature:
            name: DNS
            state: present
          when: module_available.stdout | trim | bool
          register: dns_install

        - name: Reboot server if needed
          win_reboot:
          when: dns_install.reboot_required | bool

        - name: Clean slate
          import_tasks: tasks/clean.yml
          vars:
            fail_on_missing: no

        - name: Create the forward zone
          win_shell: >-
            Add-DnsServerPrimaryZone -Name \
            '{{ win_dns_record_zone }}' -ZoneFile '{{ win_dns_record_zone}}.dns'

        - name: Create the reverse zone
          win_shell: >-
            Add-DnsServerPrimaryZone -NetworkID \
            '{{ win_dns_record_revzone_network }}' -ZoneFile '{{ win_dns_record_revzone}}.dns'

    - name: Prepare DNS records for testing
      block:

        - name: 'Prepare win_dns_records - remove records'
          vars:
            win_dns_records:
            - zone: '{{ win_dns_record_zone }}'
              name: test1
              type: A
              state: absent
          include_role:
            name: amtega.win_dns_records
            allow_duplicates: yes

        - name: 'Prepare win_dns_records - add records - test1'
          vars:
            win_dns_records:
            - zone: '{{ win_dns_record_zone }}'
              name: test1
              value: 1.2.3.1
              type: A
              state: present
          include_role:
            name: amtega.win_dns_records
            allow_duplicates: yes

        - name: 'Prepare win_dns_records - add records - test2'
          vars:
            win_dns_records:
            - zone: '{{ win_dns_record_zone }}'
              name: test2
              value: 1.2.3.2
              type: A
              state: present
          include_role:
            name: amtega.win_dns_records
            allow_duplicates: yes

        - name: 'Prepare win_dns_records - add records - test3'
          vars:
            win_dns_records:
            - zone: '{{ win_dns_record_zone }}'
              name: test3
              value: 1.2.3.3
              type: A
              state: present
          include_role:
            name: amtega.win_dns_records
            allow_duplicates: yes

        - name: 'Prepare win_dns_records - add records - test4'
          vars:
            win_dns_records:
            - zone: '{{ win_dns_record_zone }}'
              name: test3
              value: 1.2.3.4
              type: A
              state: present
          include_role:
            name: amtega.win_dns_records
            allow_duplicates: yes
